src/Entity/Position.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\PositionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PositionRepository::class)]
#[ApiResource]
class Position
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    // Relation ManyToMany avec l'entité Team, inversée par le champ 'positions'
    #[ORM\ManyToMany(targetEntity: Team::class, inversedBy: 'positions')]
    private Collection $users;

    #[ORM\Column(length: 255)]
    private ?string $Label = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Team>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Team $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(Team $user): static
    {
        $this->users->removeElement($user);

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->Label;
    }

    public function setLabel(string $Label): static
    {
        $this->Label = $Label;

        return $this;
    }
}

src/Entity/Team.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
#[ApiResource]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    // Relation ManyToMany avec l'entité Position, utilisant le champ 'users' de Position
    #[ORM\ManyToMany(targetEntity: Position::class, mappedBy: 'users')]
    private Collection $positions;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Âge = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Tel = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Mail = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CV = null;

    #[ORM\Column(nullable: true)]
    private ?int $manager_id = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    public function __construct()
    {
        $this->positions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Position>
     */
    public function getPositions(): Collection
    {
        return $this->positions;
    }

    public function addPosition(Position $position): static
    {
        if (!$this->positions->contains($position)) {
            $this->positions->add($position);
            $position->addUser($this);
        }

        return $this;
    }

    public function removePosition(Position $position): static
    {
        if ($this->positions->removeElement($position)) {
            $position->removeUser($this);
        }

        return $this;
    }

    public function getÂge(): ?string
    {
        return $this->Âge;
    }

    public function setÂge(?string $Âge): static
    {
        $this->Âge = $Âge;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(?string $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): static
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(?string $Mail): static
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getCV(): ?string
    {
        return $this->CV;
    }

    public function setCV(?string $CV): static
    {
        $this->CV = $CV;

        return $this;
    }

    public function getManagerId(): ?int
    {
        return $this->manager_id;
    }

    public function setManagerId(?int $manager_id): static
    {
        $this->manager_id = $manager_id;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Repository\TeamRepository;
use App\Entity\Team;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\PositionRepository;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\VarDumper\VarDumper;

class DefaultController extends AbstractController
{
    #[Route('/default', name: 'app_default')]
    public function index(TeamRepository $repository, PositionRepository $positionRepository): Response
    {
        // Récupération de tous les membres de l'équipe et de toutes les positions
        $team = $repository->findAll();
        $positions = $positionRepository->findAll();

        // Créer des tableaux pour chaque groupe en fonction de la position
        $managerGroup = [];
        $secondRankGroup = [];
        $thirdRankGroup = [];
        $fourthRankGroup = [];

        foreach ($team as $teamMember) {
            dump($teamMember); // Afficher le membre de l'équipe (pour le débogage)

            // Récupérer toutes les positions de l'équipe
            $positions = $teamMember->getPositions();

            // Pour trouver le manager correspondant
            $managerId = $teamMember->getManagerId();
            if ($managerId !== null) {
                $manager = $repository->find($managerId);
                if ($manager) {
                    $managerPosition = $manager->getPositions()[0]->getLabel();
                    $teamMember->managerPosition = $managerPosition;
                }
            }

            // Parcourir les positions de l'équipe et les trier dans les groupes appropriés
            foreach ($positions as $position) {
                if ($position->getId() == 1) {
                    $managerGroup[] = $teamMember;
                } elseif ($position->getId() == 4 || $position->getId() == 3 || $position->getId() == 2) {
                    $secondRankGroup[] = $teamMember;
                } elseif ($position->getId() == 5 || $position->getId() == 6 || $position->getId() == 7) {
                    $thirdRankGroup[] = $teamMember;
                } elseif ($position->getId() == 8) {
                    $fourthRankGroup[] = $teamMember;
                }
            }
        }

        // Afficher les groupes (pour le débogage)
        dump($managerGroup);
        dump($secondRankGroup);
        dump($thirdRankGroup);
        dump($fourthRankGroup);
        dump($team);
        // die('Reached here.'); // Arrêter l'exécution ici (pour le débogage)

        // Rendre le template en passant les données nécessaires
        return $this->render('default/index.html.twig', [
            'managerGroup' => $managerGroup,
            'secondRankGroup' => $secondRankGroup,
            'thirdRankGroup' => $thirdRankGroup,
            'fourthRankGroup' => $fourthRankGroup,
            'positions' => $positions,
        ]);
    }

    
    #[Route('default/shows/{id}', name: 'app_shows')]
    public function shows(TeamRepository $teamRepository, PositionRepository $positionRepository, int $id): Response
    {
        $team = $teamRepository->findOneBy(["id" => $id]);
        $position = $positionRepository->findOneBy(["id" => $id]);

        return $this->render('default/shows.html.twig', [
            'team' => $team,
            'position' => $position,
        ]);
    }
    
    #[Route('/team', name: 'team', methods: ['GET'])]
    public function team(PositionRepository $positionRepository): Response 
    {
        $positions = $positionRepository->findAll();
            
        return $this->render('team/index.html.twig', [
            'positions' => $positions,
        ]);
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/shows.css') }}">



{% endblock %}

{% block body %}
    <h1 class="title">
        Organigramme hiérarchique Symfony Twig
    </h1>
    <div class="org"> 
        {# Rang 1 : Gérant #}
        <div class="rang-1">
            {% for team in managerGroup %}
                <div class="manager"id="team-member-{{ team.id }}">
                    <a href="{{ path('app_shows', { 'id': team.id }) }}">
                        <img src="{{ asset(team.photo) }}" alt="{{ team.firstname }} {{ team.lastname }}">
                        <h3>{{ team.firstname }} {{ team.lastname }}</h3>
                        {{ team.positions[0].label }}
                    </a>
                </div>
            {% endfor %}
        </div>

        {# Rang 2 : Commercial, Comptabilité, Lead Dev #}
        <div class="rang-2">
            {% for team in secondRankGroup %}
                <div class="position-of-2nd-rank"id="team-member-{{ team.id }}">
                    <a href="{{ path('app_shows', { 'id': team.id }) }}">
                        <img src="{{ asset(team.photo) }}" alt="{{ team.firstname }} {{ team.lastname }}">
                        <h3>{{ team.firstname }} {{ team.lastname }}</h3>
                        {{ team.positions[0].label }}
                    </a>
                </div>
            {% endfor %}
        </div>

        {# Rang 3 : Dev, UI/UX #}
        <div class="rang-3">
            {% for team in thirdRankGroup %}
                <div class="position-of-3rd-rank"id="team-member-{{ team.id }}">
                    <a href="{{ path('app_shows', { 'id': team.id }) }}">
                        <img src="{{ asset(team.photo) }}" alt="{{ team.firstname }} {{ team.lastname }}">
                        <h3>{{ team.firstname }} {{ team.lastname }}</h3>
                        {{ team.positions[0].label }}
                    </a>
                </div>
            {% endfor %}
        </div>

        {# Rang 4 : Stagiaire #}
        <div class="rang-4">
            {% for team in fourthRankGroup %}
                <div class="stagiaire"id="team-member-{{ team.id }}">
                    <a href="{{ path('app_shows', { 'id': team.id }) }}">
                        <img src="{{ asset(team.photo) }}" alt="{{ team.firstname }} {{ team.lastname }}">
                        <h3>{{ team.firstname }} {{ team.lastname }}</h3>
                        {{ team.positions[0].label }}
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

templates/default/shows.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ asset('css/shows.css') }}">
        {% endblock %}
{% block title %}Hello DefaultController!{% endblock %}

{% block body %}
<div class= "">
<img src = "{{asset(team.photo)}}"
<h1> {{ team.firstname}} {{ team.lastname}} : {% for position in team.positions %} {{position.label}}
    
{% endfor %}</h1>

<h2>Age : {{ team.Âge }}</h2>
                &nbsp;
                <h3>Adresse : {{ team.adresse}}</h3>
                &nbsp;
                <h4>Telephone : {{ team.tel}}</h4>
                &nbsp;
               

                 {% if team.mail %}
            <h4>Email : <a href="mailto:{{ team.mail }}">{{ team.mail }}</a></h4>
        {% endif %}

                {% if team.cv %}
            <h4>CV : <a href="{{ asset(team.cv) }}">Télécharger le CV</a></h4>
        {% endif %}
</div>

{% endblock %}